### ISSUE TITLE
Getting a build error when running `cargo install tuc --features regex`

### ISSUE THREAD

**Issue by gleenn** [riquito/tuc#52]
$> cargo install tuc --features regex
    Updating crates.io index
  Installing tuc v0.10.0
  Downloaded regex v1.5.6
  Downloaded regex-syntax v0.6.26
  Downloaded memchr v2.5.0
  Downloaded 3 crates (598.3 KB) in 1.42s
   Compiling memchr v2.5.0
   Compiling anyhow v1.0.57
   Compiling regex-syntax v0.6.26
   Compiling pico-args v0.5.0
   Compiling aho-corasick v0.7.18
   Compiling regex v1.5.6
   Compiling tuc v0.10.0
error[E0716]: temporary value dropped while borrowed
   --> /Users/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tuc-0.10.0/src/bin/tuc.rs:200:45
    |
200 |     let mut stdin = std::io::BufReader::new(std::io::stdin().lock());
    |                                             ^^^^^^^^^^^^^^^^        - temporary value is freed at the end of this statement
    |                                             |
    |                                             creates a temporary which is freed while still in use
...
204 |         read_and_cut_bytes(&mut stdin, &mut stdout, &opt)?;
    |                            ---------- borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value

error[E0716]: temporary value dropped while borrowed
   --> /Users/glenn/.cargo/registry/src/github.com-1ecc6299db9ec823/tuc-0.10.0/src/bin/tuc.rs:201:46
    |
201 |     let mut stdout = std::io::BufWriter::new(std::io::stdout().lock());
    |                                              ^^^^^^^^^^^^^^^^^        - temporary value is freed at the end of this statement
    |                                              |
    |                                              creates a temporary which is freed while still in use
...
204 |         read_and_cut_bytes(&mut stdin, &mut stdout, &opt)?;
    |                                        ----------- borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: failed to compile `tuc v0.10.0`, intermediate artifacts can be found at `/var/folders/tm/w39t83zs2fj8yhzd7tnvggh40000gn/T/cargo-installHSlmRF`

Caused by:
  could not compile `tuc` due to 2 previous errors

**Comment by gleenn** [comment]
Figured it out, apparently this project requires rust 1.61.0 (or at least, it definitely doesn't work on 1.59.0).
